[package]
name = "irirserver"
version = "0.0.0"
authors = ["Hentioe <me@bluerain.io>"]
edition = "2018"

[dependencies]
libcore = { path="../libcore" }
libresizer = { path="../libresizer" }
actix-web = "0.7.13"
lazy_static = "1.2.0"
clap = "2.32.0"