[package]
name = "irirserver"
version = "0.0.0"
authors = ["Hentioe <me@bluerain.io>"]
edition = "2018"

[dependencies]
libcore = { path="../libcore" }
libresizer = { path="../libresizer" }
failure = "0.1.4"
actix-web = "0.7.17"
lazy_static = "1.2.0"
clap = "2.32.0"
env_logger = "0.6.0"
log = "0.4.6"
regex = "1.1.0"